sudo: required
language: ruby
cache: bundler
dist: trusty

rvm:
  - 2.5.0

services:
  - postgresql
env:
  DISPLAY: :99.0
  CHROME_DRIVER_VERSION: '2.38'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp ./.travis/database.yml.travis config/database.yml
  - bundle install
  - bin/setup_travis

script:
  - bundle exec rails test:system
