sudo: required
language: ruby
cache: bundler
dist: trusty

rvm:
  - 2.5.5
  - 2.6.3
  - ruby-head

services:
  - postgresql

env:
  DISPLAY: :99.0
  CHROME_DRIVER_VERSION: '75.0.3770.8'

addons:
  chrome: stable
  postgresql: '9.4'

before_install:
  - gem install bundler:1.17.2

before_script:
  - bin/setup_travis
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp ./.travis/database.yml.travis config/database.yml
  - bundle install
  - RAILS_ENV=test bundle exec rails db:create
  - RAILS_ENV=test bundle exec rails db:migrate

script:
  - bundle exec rails test:system
