sudo: required
language: ruby
cache: bundler
dist: trusty

rvm:
  - 2.5.0

services:
  - postgresql
env:
  DISPLAY: :99.0
  CHROME_DRIVER_VERSION: '2.38'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp ./.travis/database.yml.travis config/database.yml
  - bundle install
  - gem install chromium
  - wget "http://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo apt-get install libnss3
  - sudo apt-get --only-upgrade install google-chrome-stable
  - sudo cp chromedriver /usr/local/bin/.
  - sudo chmod +x /usr/local/bin/chromedriver
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - bundle exec rails test:system
