default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: favoreyo_development

test:
  <<: *default
  database: favoreyo_test

production:
  <<: *default
  database: favoreyo_production
  username: favoreyo
  password: <%= ENV['FAVOREYO_DATABASE_PASSWORD'] %>
