on:
  pull_request:
    types: [opened, synchronize]
jobs:
  run-test:
    name: Run System Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout pushed commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: create test database for test
        run: docker compose run app bin/rails db:setup
        working-directory: ./

      - name: run test on docker-compose
        run: docker compose run app bin/rails test:system
        working-directory: ./
